org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=thgw
mod.name=Tactical Happy Ghast Warfare
mod.group=me.pajic
mod.version=1.2.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Launch TNT from your happy ghast with a little help from a villager
mod.sources_url=https://github.com/pajicadvance/thgw
mod.homepage_url=https://modrinth.com/mod/thgw
mod.issues_url=https://github.com/pajicadvance/thgw/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=QJhhMcSO
publish.curseforge=1275568
publish.github=false
